#!/usr/bin/python3
# factors.py

import math

def factorize_number(n):
    factors = []
    for i in range(2, int(math.sqrt(n)) + 1):
        while n % i == 0:
            factors.append(i)
            n //= i
    if n > 1:
        factors.append(n)
    return factors

def factorize_file(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            num = int(line.strip())
            factors = factorize_number(num)
            print(f"{num}={'*'.join(map(str, factors))}")

if __name__ == "__main__":
    factorize_file("tests/test00")

